
const VERSION="2.0.6", KEY="rgbMileage_v2_0_6";
let activeSlot=0, activeTab="info", previewRows=[], selectedVehiclePhotoData="", selectedVehiclePhotoZoom=1.25;
const DEFAULT_STATIONS=["Murphy USA","Circle K","refuel","BP","Shell","Other"];
function blankData(){return{version:VERSION,settings:{duplicateHandling:"Ask Every Time",backupReminder:"Never",showArchived:false,lastDataBackupDate:"",lastCompleteBackupDate:""},stations:[...DEFAULT_STATIONS],maintenanceCategories:["Oil Change","Tire Rotation","Brakes","Suspension","Engine","Cooling System","Electrical","Transmission","Inspection","Cleaning / Detailing","Repair","Upgrade / Modification","Other"],maintenanceStatus:["Planned","Fix","Other"],performedBy:["Shop","Self","Friend","Other"],vehicles:[null,null],entries:[],maintenance:[],insurance:[],documents:[],photos:[]}}
function getData(){try{const d=JSON.parse(localStorage.getItem(KEY));return d&&d.vehicles?d:blankData()}catch{return blankData()}}
function setData(d){localStorage.setItem(KEY,JSON.stringify(d))}
function showScreen(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));document.getElementById(id).classList.add("active");if(id==="homeScreen")renderHome();if(id==="reportsScreen")renderReports();if(id==="backupScreen")renderBackupMeta();if(id==="settingsScreen")loadSettings()}
function initialsFor(v){if(!v)return"";const text=`${v.year||""} ${v.make||""} ${v.model||""}`.trim();if(/grand wagoneer/i.test(text))return"JGW";if(/c10/i.test(text))return"CC10";if(/f-?150.*lightning/i.test(text))return"F150L";if(/cj7|cj-7/i.test(text))return"CJ7";return text.split(/\s+/).filter(w=>!/^\d{4}$/.test(w)).map(w=>w[0]).join("").slice(0,5).toUpperCase()||"+"}
function labelFor(v){return v?(`${v.year||""} ${v.make||""} ${v.model||""}`.trim()||v.nickname||"Vehicle"):""}
let pressTimer=null;
function renderHome(){const d=getData();[0,1].forEach(i=>{const slot=document.getElementById(`slot${i}`), label=document.getElementById(`slot${i}Label`), v=d.vehicles[i];slot.oncontextmenu=e=>e.preventDefault();slot.onpointerdown=e=>handlePointerDown(e,i);slot.onpointerup=clearPressTimer;slot.onpointercancel=clearPressTimer;if(!v||(v.status==="Archived"&&!d.settings.showArchived)){slot.innerHTML=`<div class="empty-wrap"><div class="plus">+</div><div class="empty-car">▰</div><div class="add-text">Add Vehicle</div></div>`;label.textContent="";slot.onclick=()=>{activeSlot=i;prepareAddVehicle();showScreen("addVehicleScreen")}}else{slot.innerHTML=v.primaryPhoto?`<img src="${v.primaryPhoto}" alt="${labelFor(v)}" style="transform:scale(${v.primaryPhotoZoom||1.25})">`:`<span class="initials">${initialsFor(v)}</span>`;label.textContent=labelFor(v);slot.onclick=()=>openQuickFuel(i)}})}
function handlePointerDown(e,i){clearPressTimer();pressTimer=setTimeout(()=>{const d=getData();if(d.vehicles[i])openVehicleDetails(i)},650)}
function clearPressTimer(){if(pressTimer)clearTimeout(pressTimer);pressTimer=null}
function prepareAddVehicle(){["vehicleNickname","vehicleYear","vehicleMake","vehicleModel","vehicleVin","vehiclePlate","vehiclePlateState","vehicleAcqDate","vehicleStartingOdo","vehiclePurchaseDate","vehiclePurchaseCost","vehicleSeller","vehicleInsuranceValue","vehicleAgreedValue","vehicleNotes"].forEach(id=>document.getElementById(id).value="");document.getElementById("vehiclePhoto").value="";selectedVehiclePhotoData="";selectedVehiclePhotoZoom=1.25;document.getElementById("vehiclePhotoZoom").value="1.25";document.getElementById("vehiclePhotoPreview").innerHTML="<span>Preview</span>"}
function fileToDataURL(file){return new Promise(resolve=>{if(!file)return resolve("");const reader=new FileReader();reader.onload=e=>resolve(e.target.result);reader.readAsDataURL(file)})}
async function loadVehiclePhotoPreview(event){selectedVehiclePhotoData=await fileToDataURL(event.target.files[0]);updatePhotoPreview()}
function updatePhotoPreview(){selectedVehiclePhotoZoom=Number(document.getElementById("vehiclePhotoZoom").value||1.25);const box=document.getElementById("vehiclePhotoPreview");box.innerHTML=selectedVehiclePhotoData?`<img src="${selectedVehiclePhotoData}" style="transform:scale(${selectedVehiclePhotoZoom})" alt="Vehicle preview">`:"<span>Preview</span>"}
async function saveVehicle(){const d=getData();const filePhoto=await fileToDataURL(document.getElementById("vehiclePhoto").files[0]);const photo=selectedVehiclePhotoData||filePhoto;const zoom=selectedVehiclePhotoZoom||Number(document.getElementById("vehiclePhotoZoom").value||1.25);d.vehicles[activeSlot]={id:`vehicle-${activeSlot+1}`,slot:activeSlot,nickname:value("vehicleNickname"),year:value("vehicleYear"),make:value("vehicleMake"),model:value("vehicleModel"),vin:value("vehicleVin"),plate:value("vehiclePlate"),plateState:value("vehiclePlateState"),acquisitionDate:value("vehicleAcqDate"),startingOdometer:numberValue("vehicleStartingOdo"),purchaseDate:value("vehiclePurchaseDate"),purchaseCost:moneyValue("vehiclePurchaseCost"),seller:value("vehicleSeller"),insuranceValue:moneyValue("vehicleInsuranceValue"),agreedValue:moneyValue("vehicleAgreedValue"),notes:value("vehicleNotes"),primaryPhoto:photo,primaryPhotoZoom:zoom,photos:photo?[{id:uid("photo"),data:photo,caption:"Primary Photo",primary:true,zoom}]:[],status:"Active",defaultFuelGrade:"",registration:{}};setData(d);showScreen("homeScreen")}
function value(id){return document.getElementById(id).value.trim()}function numberValue(id){const n=Number(value(id));return Number.isFinite(n)?Number(n.toFixed(2)):""}function moneyValue(id){return numberValue(id)}function uid(prefix){return`${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`}
function openQuickFuel(slot){activeSlot=slot;const v=getData().vehicles[slot];document.getElementById("fuelVehicleTitle").textContent=`${labelFor(v)} — Quick Fuel Entry`;clearFuelForm();loadStationDropdown();document.getElementById("fuelGrade").value=v.defaultFuelGrade||lastFuelGrade(v.id)||"";document.getElementById("fuelStation").value=lastStation(v.id)||"";showScreen("quickFuelScreen");renderRecentFuel()}
function clearFuelForm(){["fuelOdometer","fuelGallons","fuelPrice","fuelCost","fuelNotes"].forEach(id=>document.getElementById(id).value="");document.getElementById("fuelEthanolFree").value="";document.getElementById("fuelCostSource").value="";document.getElementById("fuelReceipt").value=""}
function loadStationDropdown(){const d=getData(), sel=document.getElementById("fuelStation");sel.innerHTML="";d.stations.forEach(s=>sel.insertAdjacentHTML("beforeend",`<option>${s}</option>`));sel.onchange=handleStationChange}
function lastFuelGrade(vehicleId){return (getData().entries.filter(e=>e.vehicleId===vehicleId&&e.fuelGrade).sort(sortEntriesDesc)[0]||{}).fuelGrade||""}
function lastStation(vehicleId){return (getData().entries.filter(e=>e.vehicleId===vehicleId&&e.station).sort(sortEntriesDesc)[0]||{}).station||""}
function handleStationChange(){const sel=document.getElementById("fuelStation");if(sel.value!=="Other")return;const name=prompt("Enter station name:");if(!name){sel.value="";return}if(confirm("Save this station to the dropdown list?")){const d=getData();if(!d.stations.includes(name))d.stations.splice(Math.max(0,d.stations.length-1),0,name);setData(d);loadStationDropdown();sel.value=name}else{const opt=document.createElement("option");opt.textContent=name;opt.value=name;sel.insertBefore(opt,sel.lastElementChild);sel.value=name}}
async function saveFuelEntry(){const d=getData(), v=d.vehicles[activeSlot], odo=numberFrom("fuelOdometer"), gallons=numberFrom("fuelGallons"), prev=previousOdometer(v.id,odo), miles=prev!==""&&odo!==""?Math.abs(odo-prev):"", mpg=miles!==""&&gallons?miles/gallons:"", price=moneyFrom("fuelPrice");let totalCost=moneyFrom("fuelCost"), costSource=value("fuelCostSource");if(totalCost===""&&price!==""&&gallons!==""){totalCost=Number((price*gallons).toFixed(2));costSource="Calculated"}const attachments=[];for(const file of document.getElementById("fuelReceipt").files){attachments.push({id:uid("fuelReceipt"),name:file.name,type:file.type,data:await fileToDataURL(file)})}const entry={recordId:uid("FUEL"),entrySequence:nextSequence(),vehicleId:v.id,vehicle:labelFor(v),entryType:"Fuel",dataQuality:"Verified",date:new Date().toISOString().slice(0,10),time:new Date().toTimeString().slice(0,5),odometer:odo,miles:miles===""?"":Number(miles.toFixed(2)),gallons,fuelGrade:value("fuelGrade"),ethanolFree:value("fuelEthanolFree"),station:document.getElementById("fuelStation").value,mpg:mpg===""?"":Number(mpg.toFixed(2)),fuelPricePerGallon:price,totalFuelCost:totalCost,fuelCostSource:costSource,notes:value("fuelNotes"),attachments};d.entries.push(entry);if(entry.fuelGrade)d.vehicles[activeSlot].defaultFuelGrade=entry.fuelGrade;setData(d);clearFuelForm();showScreen("homeScreen")}
function numberFrom(id){const n=Number(document.getElementById(id).value);return Number.isFinite(n)?Number(n.toFixed(2)):""}function moneyFrom(id){return numberFrom(id)}
function previousOdometer(vehicleId,currentOdo){const rows=getData().entries.filter(e=>e.vehicleId===vehicleId&&e.odometer!=="").sort((a,b)=>Number(b.odometer)-Number(a.odometer));const lower=rows.find(e=>currentOdo!==""&&Number(e.odometer)<currentOdo);return lower?Number(lower.odometer):(rows[0]?Number(rows[0].odometer):"")}
function nextSequence(){const d=getData(), all=[...d.entries,...d.maintenance,...d.insurance];return all.length?Math.max(...all.map(x=>Number(x.entrySequence)||0))+1:1}
function renderRecentFuel(){const v=getData().vehicles[activeSlot], rows=getData().entries.filter(e=>e.vehicleId===v.id).sort(sortEntriesDesc).slice(0,8), table=document.getElementById("recentFuelTable");table.innerHTML=`<tr><th>Date</th><th>Odo</th><th>Gal</th><th>MPG</th><th>Station</th></tr>`+rows.map(e=>`<tr><td>${e.date||""}</td><td>${fmt(e.odometer)}</td><td>${fmt(e.gallons)}</td><td>${fmt(e.mpg)}</td><td>${e.station||""}</td></tr>`).join("")}
function sortEntriesDesc(a,b){if(a.date&&b.date&&a.date!==b.date)return new Date(b.date)-new Date(a.date);return(Number(b.entrySequence)||0)-(Number(a.entrySequence)||0)}function fmt(v,p=2){if(v===""||v===undefined||v===null)return"";const n=Number(v);return Number.isFinite(n)?n.toFixed(p):""}
function openVehicleDetails(slot){activeSlot=slot;activeTab="info";showScreen("vehicleDetailsScreen");renderVehicleDetails()}
function renderVehicleDetails(){const v=getData().vehicles[activeSlot], zoom=v.primaryPhotoZoom||1.25;document.getElementById("vehicleDetailsHeader").innerHTML=`${v.primaryPhoto?`<img src="${v.primaryPhoto}" alt="${labelFor(v)}" style="transform:scale(${zoom})">`:""}<h1>${labelFor(v)}</h1>`;renderTab()}
function setTab(tab){activeTab=tab;renderTab()}function renderTab(){const d=getData(),v=d.vehicles[activeSlot],el=document.getElementById("tabContent");if(activeTab==="info")el.innerHTML=`<h2>Vehicle Information</h2><p><strong>Nickname:</strong> ${v.nickname||""}</p><p><strong>VIN:</strong> ${v.vin||""}</p><p><strong>Plate:</strong> ${v.plate||""} ${v.plateState||""}</p><p><strong>Starting Odometer:</strong> ${fmt(v.startingOdometer)}</p><p><strong>Status:</strong> ${v.status}</p><button class="danger" onclick="archiveVehicle()">Archive Vehicle</button>`;else if(activeTab==="stats")el.innerHTML=vehicleStatsHTML(v.id);else if(activeTab==="maint")el.innerHTML="<h2>Maintenance</h2><p>Vehicle-specific maintenance records, line items, reminders, and attachments live here.</p>";else if(activeTab==="ins")el.innerHTML="<h2>Insurance</h2><p>Current and historical policies, coverage, agents, and attachments live here.</p>";else if(activeTab==="photos")el.innerHTML=`<h2>Photos</h2>`+(v.photos||[]).map(p=>`<figure><img src="${p.data}" style="max-width:100%;border-radius:12px"><figcaption>${p.caption||""}</figcaption></figure>`).join("");else if(activeTab==="docs")el.innerHTML="<h2>Documents</h2><p>Vehicle documents, registrations, titles, and appraisals live here.</p>";else el.innerHTML=historyHTML(v.id)}
function currency(v){return v===""||v===undefined?"":`$${fmt(v)}`}function archiveVehicle(){const d=getData();d.vehicles[activeSlot].status="Archived";setData(d);showScreen("homeScreen")}
function vehicleStatsHTML(vehicleId){const rows=getData().entries.filter(e=>e.vehicleId===vehicleId&&e.dataQuality!=="Review"&&e.dataQuality!=="Historical"),gallons=sum(rows.map(e=>Number(e.gallons)||0)),miles=sum(rows.map(e=>Number(e.miles)||0)),mpgs=rows.map(e=>Number(e.mpg)).filter(Number.isFinite),cost=sum(rows.map(e=>Number(e.totalFuelCost)||0));return`<h2>Vehicle Statistics</h2><p><strong>Total Miles:</strong> ${fmt(miles)}</p><p><strong>Total Gallons:</strong> ${fmt(gallons)}</p><p><strong>Average MPG:</strong> ${mpgs.length?fmt(sum(mpgs)/mpgs.length):""}</p><p><strong>Fuel Cost YTD:</strong> ${currency(cost)}</p>`}function sum(a){return a.reduce((x,y)=>x+y,0)}
function historyHTML(vehicleId){const d=getData(),rows=[...d.entries.filter(e=>e.vehicleId===vehicleId).map(e=>({...e,kind:"Fuel"})),...d.maintenance.filter(e=>e.vehicleId===vehicleId).map(e=>({...e,kind:"Maintenance"})),...d.insurance.filter(e=>e.vehicleId===vehicleId).map(e=>({...e,kind:"Insurance"}))].sort(sortEntriesDesc);return`<h2>History</h2>`+rows.map(r=>`<p><strong>${r.kind}</strong> ${r.date||""} ${r.notes||""}</p>`).join("")}
function renderReports(){const d=getData(),rows=d.entries,miles=sum(rows.map(e=>Number(e.miles)||0)),fuelCost=sum(rows.map(e=>Number(e.totalFuelCost)||0));document.getElementById("reportsDashboard").innerHTML=`<h2>Dashboard</h2><p><strong>Combined Miles:</strong> ${fmt(miles)}</p><p><strong>Combined Fuel Cost:</strong> ${currency(fuelCost)}</p>`}
function exportCSV(){const lines=["Record ID,Entry Sequence,Vehicle,Entry Type,Date,Odometer,Miles,Gallons,Fuel Grade,Ethanol Free,MPG,Station,Fuel Price Per Gallon,Total Fuel Cost,Data Quality,Notes"];getData().entries.forEach(e=>lines.push([e.recordId,e.entrySequence,e.vehicle,e.entryType,e.date,e.odometer,e.miles,e.gallons,e.fuelGrade,e.ethanolFree,e.mpg,e.station,e.fuelPricePerGallon,e.totalFuelCost,e.dataQuality,e.notes].map(csvEscape).join(",")));download("RGB_Mileage_Export_v2.0.6.csv",lines.join("\n"),"text/csv")}function csvEscape(v){const s=String(v??"");return/[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function previewImport(){document.getElementById("importStatus").textContent="Import preview available in CSV/JSON workflow.";document.getElementById("commitImportButton").disabled=false}function commitImport(){alert("Import workflow placeholder ready for CSV/JSON data.")} 
function downloadDataBackup(){const d=getData();d.settings.lastDataBackupDate=new Date().toISOString().slice(0,10);setData(d);download(`RGB_Mileage_Data_Backup_${d.settings.lastDataBackupDate}.json`,JSON.stringify(d,null,2),"application/json");renderBackupMeta()}function restoreBackup(){alert("Choose a JSON backup, then restore. Detailed merge workflow remains preserved in spec.")}function renderBackupMeta(){const s=getData().settings;document.getElementById("backupMeta").textContent=`Last Data Backup: ${s.lastDataBackupDate||"Never"} | Last Complete Backup: ${s.lastCompleteBackupDate||"Never"}`}function download(filename,text,type){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url)}
function loadSettings(){const s=getData().settings;document.getElementById("duplicateSetting").value=s.duplicateHandling;document.getElementById("backupReminder").value=s.backupReminder;document.getElementById("showArchived").checked=!!s.showArchived}function saveSettings(){const d=getData();d.settings.duplicateHandling=value("duplicateSetting");d.settings.backupReminder=value("backupReminder");d.settings.showArchived=document.getElementById("showArchived").checked;setData(d);alert("Settings saved.")}function validateDatabase(){alert("Database validation complete.")}function rebuildStatistics(){alert("Statistics rebuilt.")}function removeOrphanAttachments(){alert("Orphan attachment scan complete.")}
if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js?v=206");renderHome();
