/* RGB Mileage v2.1.0 - app.js
 * FUNCTION INDEX:
 * 1 Constants/State
 * 2 Storage/Migration
 * 3 UI helpers
 * 4 Vehicle module
 * 5 Universal record helpers
 * 6 Fuel module
 * 7 Maintenance module
 * 8 Insurance module
 * 9 Data/Backup/Import
 * 10 Reports/Settings
 */
const VERSION="2.1.0", BUILD_DATE="2026-06-05", KEY="RGBM_DATA_v210";
const LEGACY_KEYS=["rgbMileage","rgbm_data_v110","rgbMileage_v2_0_6","rgbMileage_v2_0_7","rgbMileage_v2_0_8","rgbMileage_v2_0_9","rgbMileage_v2_0_10","rgbMileage_v2_0_11"];
const STATIONS_DEFAULT=["Murphy USA","Circle K","refuel","BP","Shell","Other"];
const DATA_QUALITIES=["Verified","Review","Estimated"];
const TAGS=["Imported","Historical","Archived"];
const FUEL_GRADES=["","87","89","90","91","93","Other"];
let state, route={screen:"home"}, longPressTimer=null, suppressTap=false;

function nowISO(){return new Date().toISOString()}
function uid(prefix="ID"){return prefix+"-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,8)}
function blankData(){return {app:"RGB Mileage",schemaVersion:"2.1.0",appVersion:VERSION,createdAt:nowISO(),modifiedAt:nowISO(),settings:{lastBackupDate:"",lastBackupFilename:"",showArchived:false},nextEntrySequence:1,stations:[...STATIONS_DEFAULT],vehicles:[null,null],vehicleAcquisitionRecords:[],fuelRecords:[],maintenanceRecords:[],insuranceRecords:[],attachments:[],metadata:{}}}
function loadData(){let raw=localStorage.getItem(KEY); if(raw){try{return normalizeData(JSON.parse(raw))}catch(e){console.warn(e)}} for(const k of LEGACY_KEYS){raw=localStorage.getItem(k); if(raw){try{const d=normalizeData(JSON.parse(raw)); saveData(d); return d}catch(e){console.warn(e)}}} const d=blankData(); saveData(d); return d}
function saveData(d=state){d.modifiedAt=nowISO();d.schemaVersion="2.1.0";d.appVersion=VERSION;localStorage.setItem(KEY,JSON.stringify(d));state=d}
function seq(){const n=state.nextEntrySequence||1; state.nextEntrySequence=n+1; return n}
function arr(v){return Array.isArray(v)?v:[]}
function tags(v){return Array.isArray(v)?v:(v?[String(v)]:[])}
function hasTag(r,t){return tags(r.classificationTags).includes(t)}
function addTag(r,t){r.classificationTags=tags(r.classificationTags); if(!r.classificationTags.includes(t))r.classificationTags.push(t)}
function remTag(r,t){r.classificationTags=tags(r.classificationTags).filter(x=>x!==t)}
function numVal(v){if(v===null||v===undefined||v==="")return ""; const n=Number(String(v).replace(/[$,]/g,"")); return Number.isFinite(n)?n:""}
function baseRecord(type,vehicleId,source="Manual Entry"){return {recordId:uid(type.toUpperCase()),entrySequence:seq(),recordType:type,vehicleId,source,classificationTags:[],dataQuality:source==="Manual Entry"?"Verified":"Review",createdAt:nowISO(),modifiedAt:nowISO(),notes:""}}
function normalizeData(input){const d=blankData(); if(!input||typeof input!=="object")return d; d.settings={...d.settings,...(input.settings||{})}; d.stations=Array.isArray(input.stations)&&input.stations.length?input.stations:[...STATIONS_DEFAULT]; if(!d.stations.includes("Other"))d.stations.push("Other"); d.nextEntrySequence=Number(input.nextEntrySequence)||1; d.vehicles=(input.vehicles||[]).slice(0,2).map((v,i)=>v?normVehicle(v,i):null); while(d.vehicles.length<2)d.vehicles.push(null); d.vehicleAcquisitionRecords=arr(input.vehicleAcquisitionRecords).map(r=>normRecord(r,"VehicleAcquisition",r.vehicleId)); d.fuelRecords=arr(input.fuelRecords||input.entries).map(r=>normFuel(r,r.vehicleId)); d.maintenanceRecords=arr(input.maintenanceRecords||input.maintenance).map(r=>normMaint(r,r.vehicleId)); d.insuranceRecords=arr(input.insuranceRecords||input.insurance).map(r=>normIns(r,r.vehicleId)); if(input.vehicles&&!input.fuelRecords&&!input.maintenanceRecords&&!input.insuranceRecords){d.vehicles=(input.vehicles||[]).slice(0,2).map((v,i)=>v?normVehicle(v,i):null); while(d.vehicles.length<2)d.vehicles.push(null); input.vehicles.slice(0,2).forEach((v,i)=>{if(!v)return; const vid=d.vehicles[i].vehicleId; if(v.acquisitionDate||v.startingOdometer||v.purchaseCost||v.purchaseDate||v.seller){d.vehicleAcquisitionRecords.push(normRecord({acquisitionDate:v.acquisitionDate||v.purchaseDate||"",startingOdometer:v.startingOdometer||"",purchasePrice:v.purchaseCost||"",seller:v.seller||"",source:"JSON Restore",dataQuality:"Review",classificationTags:["Imported"]},"VehicleAcquisition",vid))} arr(v.fuel).forEach(r=>d.fuelRecords.push(normFuel({...r,source:"JSON Restore",classificationTags:["Imported"]},vid))); arr(v.maintenance).forEach(r=>d.maintenanceRecords.push(normMaint({...r,source:"JSON Restore",classificationTags:["Imported"]},vid))); if(v.insCompany||v.policyNumber||v.insurance?.company){d.insuranceRecords.push(normIns({company:v.insCompany||v.insurance?.company||"",policyNumber:v.policyNumber||v.insurance?.policy||"",effectiveDate:v.effectiveDate||v.insurance?.effective||"",expirationDate:v.expirationDate||v.insurance?.expiration||"",coverageValue:v.insuranceValue||v.insurance?.value||"",source:"JSON Restore",classificationTags:["Imported"],dataQuality:"Review"},vid))}})} let m=0; [...d.vehicleAcquisitionRecords,...d.fuelRecords,...d.maintenanceRecords,...d.insuranceRecords].forEach(r=>m=Math.max(m,Number(r.entrySequence)||0)); d.nextEntrySequence=Math.max(d.nextEntrySequence||1,m+1); return d}
function normVehicle(v,i){return {vehicleId:v.vehicleId||v.id||uid("VEH"),slot:Number.isFinite(+v.slot)?+v.slot:i,displayName:v.displayName||[v.year,v.make,v.model].filter(Boolean).join(" ")||v.nickname||"Vehicle",nickname:v.nickname||"",year:v.year||"",make:v.make||"",model:v.model||"",badge:v.badge||"",status:v.status||"Active",primaryPhoto:v.primaryPhoto||v.photo||"",primaryPhotoZoom:Number(v.primaryPhotoZoom||v.photoZoom||1),primaryPhotoOffsetX:Number(v.primaryPhotoOffsetX||0),primaryPhotoOffsetY:Number(v.primaryPhotoOffsetY||0),createdAt:v.createdAt||nowISO(),modifiedAt:v.modifiedAt||nowISO()}}
function normRecord(r,type,vid){const rec={...r}; rec.recordType=rec.recordType||type; rec.vehicleId=rec.vehicleId||vid||""; rec.recordId=rec.recordId||rec.id||uid(type.toUpperCase()); rec.entrySequence=Number(rec.entrySequence)||seq(); rec.source=rec.source||"JSON Restore"; rec.classificationTags=tags(rec.classificationTags); rec.dataQuality=DATA_QUALITIES.includes(rec.dataQuality)?rec.dataQuality:"Review"; rec.createdAt=rec.createdAt||nowISO(); rec.modifiedAt=rec.modifiedAt||nowISO(); rec.notes=rec.notes||""; return rec}
function normFuel(r,vid){const rec=normRecord(r,"Fuel",vid); Object.assign(rec,{date:r.date||"",time:r.time||"",odometer:numVal(r.odometer),miles:numVal(r.miles||r.totalMiles),gallons:numVal(r.gallons),mpg:numVal(r.mpg),fuelGrade:r.fuelGrade||r.grade||"",ethanolFree:r.ethanolFree||"",station:r.station||"",fuelPricePerGallon:numVal(r.fuelPricePerGallon||r.price),totalFuelCost:numVal(r.totalFuelCost||r.cost),fuelCostSource:r.fuelCostSource||"",attachments:arr(r.attachments)}); if((rec.odometer!==""&&rec.miles==="")||(rec.mpg!==""&&(+rec.mpg>18||+rec.mpg<6)))addTag(rec,"Historical"); return rec}
function normMaint(r,vid){const rec=normRecord(r,"Maintenance",vid); Object.assign(rec,{dropOffDate:r.dropOffDate||r.drop||r.date||"",pickUpDate:r.pickUpDate||r.pick||"",category:r.category||r.service||"Maintenance",status:r.status||"",odometer:numVal(r.odometer),location:r.location||"",serviceProvider:r.serviceProvider||"",performedBy:r.performedBy||"",totalCost:numVal(r.totalCost||r.cost),attachments:arr(r.attachments)}); return rec}
function normIns(r,vid){const rec=normRecord(r,"Insurance",vid); Object.assign(rec,{company:r.company||"",policyNumber:r.policyNumber||r.policy||"",effectiveDate:r.effectiveDate||"",expirationDate:r.expirationDate||"",coverageValue:numVal(r.coverageValue||r.insuranceValue),agreedValue:numVal(r.agreedValue),premium:numVal(r.premium),agentName:r.agentName||"",agency:r.agency||"",phone:r.phone||"",email:r.email||"",coverageNotes:r.coverageNotes||"",attachments:arr(r.attachments)}); return rec}

function $(id){return document.getElementById(id)}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function fmt(v,d=2){return v!==""&&v!=null&&Number.isFinite(+v)?(+v).toFixed(d):""}
function money(v){return v!==""&&v!=null&&Number.isFinite(+v)?"$"+(+v).toFixed(2):""}
function nav(screen,params={}){route={screen,...params}; render(); setTimeout(()=>scrollTo(0,0),0)}
function header(title,back="home"){return '<div class="topbar"><button class="smallbtn ghost" onclick="nav(&quot;'+back+'&quot;)">Back</button><b>'+esc(title)+'</b><span></span></div>'}
function footer(){return '<div class="version">RGB Mileage v'+VERSION+' - '+BUILD_DATE+'</div>'}
function bottomNav(){return '<div class="bottom-nav"><button onclick="nav(&quot;home&quot;)">Home</button><button onclick="nav(&quot;reports&quot;)">Reports</button><button onclick="nav(&quot;data&quot;)">Data</button><button onclick="nav(&quot;settings&quot;)">Settings</button></div>'}
function vehicleLabel(v){return v?([v.year,v.make,v.model].filter(Boolean).join(" ")||v.nickname||v.displayName||"Vehicle"):"Vehicle"}
function vehicleBadge(v){if(!v)return "+"; if(v.badge)return v.badge; const s=vehicleLabel(v); if(/grand wagoneer/i.test(s))return "JGW"; if(/cj\s*7/i.test(s))return "CJ7"; return s.split(/\s+/).map(x=>x[0]).join("").slice(0,6).toUpperCase()||"+"}
function getVehicle(id){return state.vehicles.find(v=>v&&v.vehicleId===id)}
function render(){const app=$("app"); const s=route.screen; if(s==="home")return home(app); if(s==="vehicleView")return vehicleView(app,route.vehicleId); if(s==="vehicleEdit")return vehicleEdit(app,route.vehicleId,route.slot); if(s==="quickFuel")return quickFuel(app,route.vehicleId); if(s==="quickMaintenance")return quickMaintenance(app,route.vehicleId); if(s==="quickInsurance")return quickInsurance(app,route.vehicleId); if(s==="recordView")return recordView(app,route.type,route.recordId); if(s==="recordEdit")return recordEdit(app,route.type,route.recordId); if(s==="data")return dataScreen(app); if(s==="reports")return reports(app); if(s==="settings")return settings(app)}
function clearLP(){if(longPressTimer)clearTimeout(longPressTimer); longPressTimer=null}
function home(app){app.innerHTML='<h1>RGB Mileage</h1><div class="subtitle">Vehicle Record Preservation System</div><div class="stack">'+state.vehicles.map((v,i)=>circleHtml(v,i)).join("")+'</div>'+bottomNav()+footer()}
function circleHtml(v,i){const inner=v&&v.primaryPhoto?'<img src="'+v.primaryPhoto+'" alt="">':esc(vehicleBadge(v)); const label=v?vehicleLabel(v):"Add Vehicle"; return '<div class="circle-wrap" ontouchstart="lpVehicle(event,'+i+')" onmousedown="lpVehicle(event,'+i+')" ontouchend="clearLP()" onmouseup="clearLP()" onclick="tapVehicle('+i+')"><div class="circle">'+inner+'</div><div class="vehicle-label">'+esc(label)+'</div></div>'}
function tapVehicle(i){if(suppressTap){suppressTap=false;return} const v=state.vehicles[i]; if(v)nav("quickFuel",{vehicleId:v.vehicleId}); else nav("vehicleEdit",{slot:i})}
function lpVehicle(e,i){clearLP(); longPressTimer=setTimeout(()=>{suppressTap=true; const v=state.vehicles[i]; if(v)nav("vehicleView",{vehicleId:v.vehicleId}); else nav("vehicleEdit",{slot:i})},650)}
function vehicleView(app,vid){const v=getVehicle(vid); if(!v)return nav("home"); app.innerHTML=header("View Vehicle")+'<div class="card"><h2>'+esc(vehicleLabel(v))+'</h2><p>Badge: '+esc(v.badge||vehicleBadge(v))+'<br>Status: '+esc(v.status)+'</p><div class="form-actions"><button onclick="nav(&quot;vehicleEdit&quot;,{vehicleId:&quot;'+vid+'&quot;})">Edit</button><button class="danger" onclick="archiveVehicle(&quot;'+vid+'&quot;)">Archive</button></div></div><div class="card"><h2>Actions</h2><button class="wide" onclick="nav(&quot;quickFuel&quot;,{vehicleId:&quot;'+vid+'&quot;})">Quick Fuel Entry</button><button class="wide" onclick="nav(&quot;quickMaintenance&quot;,{vehicleId:&quot;'+vid+'&quot;})">Quick Maintenance Entry</button><button class="wide" onclick="nav(&quot;quickInsurance&quot;,{vehicleId:&quot;'+vid+'&quot;})">Quick Insurance Entry</button></div>'+previousRecordsHtml("Fuel",vid)+previousRecordsHtml("Maintenance",vid)+previousRecordsHtml("Insurance",vid)+bottomNav()+footer()}
function vehicleEdit(app,vid,slot=0){let v=vid?getVehicle(vid):null; if(!v)v={vehicleId:uid("VEH"),slot,status:"Active"}; app.innerHTML=header(vid?"Edit Vehicle":"Add Vehicle")+'<div class="card"><label>Year<input id="vehYear" value="'+esc(v.year||"")+'"></label><label>Make<input id="vehMake" value="'+esc(v.make||"")+'"></label><label>Model<input id="vehModel" value="'+esc(v.model||"")+'"></label><label>Badge<input id="vehBadge" value="'+esc(v.badge||"")+'"></label><label>Photo<input type="file" id="vehPhoto" accept="image/*"></label><h3>Vehicle Acquisition Record</h3><label>Acquisition Date<input type="date" id="acqDate"></label><label>Starting Odometer<input type="number" step="0.01" id="startOdo"></label><label>Purchase Price<input type="number" step="0.01" id="purchasePrice"></label><label>Seller<input id="seller"></label><button class="wide primary" onclick="saveVehicle(&quot;'+v.vehicleId+'&quot;,'+(v.slot??slot)+')">Save Vehicle</button></div>'+bottomNav()+footer()}
async function imageToData(file){return await new Promise(resolve=>{const r=new FileReader(); r.onload=e=>{const img=new Image(); img.onload=()=>{let w=img.width,h=img.height,sc=Math.min(1,1200/Math.max(w,h)); const c=document.createElement("canvas"); c.width=Math.round(w*sc); c.height=Math.round(h*sc); c.getContext("2d").drawImage(img,0,0,c.width,c.height); resolve(c.toDataURL("image/jpeg",.85))}; img.onerror=()=>resolve(e.target.result); img.src=e.target.result}; r.readAsDataURL(file)})}
async function saveVehicle(vid,slot){let v=getVehicle(vid)||{vehicleId:vid,slot,status:"Active",createdAt:nowISO()}; v.year=$("vehYear").value.trim(); v.make=$("vehMake").value.trim(); v.model=$("vehModel").value.trim(); v.badge=$("vehBadge").value.trim(); v.displayName=vehicleLabel(v); v.modifiedAt=nowISO(); const f=$("vehPhoto").files[0]; if(f)v.primaryPhoto=await imageToData(f); state.vehicles[slot]=v; if($("acqDate").value||$("startOdo").value||$("purchasePrice").value||$("seller").value){const r=baseRecord("VehicleAcquisition",vid); r.acquisitionDate=$("acqDate").value;r.startingOdometer=numVal($("startOdo").value);r.purchasePrice=numVal($("purchasePrice").value);r.seller=$("seller").value; state.vehicleAcquisitionRecords.push(r)} saveData(); alert("Vehicle saved."); nav("home")}
function archiveVehicle(vid){if(confirm("Archive vehicle?")){const v=getVehicle(vid); v.status="Archived"; v.modifiedAt=nowISO(); saveData(); nav("home")}}

function recArray(type){return type==="Fuel"?state.fuelRecords:type==="Maintenance"?state.maintenanceRecords:type==="Insurance"?state.insuranceRecords:state.vehicleAcquisitionRecords}
function records(type,vid,includeArchived=false){return recArray(type).filter(r=>(!vid||r.vehicleId===vid)&&(includeArchived||!hasTag(r,"Archived"))).sort((a,b)=>(b.entrySequence||0)-(a.entrySequence||0))}
function findRecord(type,id){return records(type,null,true).find(r=>r.recordId===id)}
function recordTitle(type,r){if(type==="Fuel")return (r.date||"No Date")+" Odo "+fmt(r.odometer); if(type==="Maintenance")return (r.dropOffDate||"No Date")+" "+(r.category||"Maintenance"); if(type==="Insurance")return (r.company||"Insurance")+" "+(r.policyNumber||""); return r.recordId}
function recordDetails(type,r){if(type==="Fuel")return "Miles: "+fmt(r.miles)+" | Gallons: "+fmt(r.gallons,3)+" | MPG: "+fmt(r.mpg)+" | Station: "+esc(r.station||"")+"<br>"+esc(r.notes||""); if(type==="Maintenance")return "Odometer: "+fmt(r.odometer)+" | Cost: "+money(r.totalCost)+"<br>"+esc(r.notes||""); if(type==="Insurance")return "Effective: "+esc(r.effectiveDate||"")+" - "+esc(r.expirationDate||"")+" | Premium: "+money(r.premium); return ""}
function previousRecordsHtml(type,vid){const rows=records(type,vid,false); return '<details class="card" open><summary><strong>Previous '+type+' Records</strong></summary>'+(rows.length?rows.map(r=>entryRow(type,r)).join(""):'<p class="muted">No records.</p>')+'</details>'}
function entryRow(type,r){const b=tags(r.classificationTags).map(t=>'<span class="badge '+(t==="Historical"?"warn":t==="Archived"?"arch":"")+'">'+esc(t)+'</span>').join(""); return '<div class="entry-row" ontouchstart="lpRecord(event,&quot;'+type+'&quot;,&quot;'+r.recordId+'&quot;)" onmousedown="lpRecord(event,&quot;'+type+'&quot;,&quot;'+r.recordId+'&quot;)" ontouchend="clearLP()" onmouseup="clearLP()" onclick="tapRecordRow(event)"><details><summary><div class="entry-main"><span>'+recordTitle(type,r)+'</span><span class="muted">'+esc(r.dataQuality)+'</span></div><div class="badges">'+b+'</div></summary><p>'+recordDetails(type,r)+'</p></details></div>'}
function lpRecord(e,type,id){clearLP(); longPressTimer=setTimeout(()=>{suppressTap=true; nav("recordView",{type,recordId:id})},650)}
function tapRecordRow(e){if(suppressTap){e.preventDefault();suppressTap=false}}
function recordMeta(r){return '<p>Record ID: '+esc(r.recordId)+'<br>Sequence: '+r.entrySequence+'<br>Source: '+esc(r.source)+'<br>Quality: '+esc(r.dataQuality)+'<br>Tags: '+esc(tags(r.classificationTags).join("; "))+'</p>'}
function commonFields(r,ro){const rd=ro?"readonly":""; const sd=ro?"disabled":""; return '<label>Data Quality<select id="rq" '+sd+'>'+DATA_QUALITIES.map(q=>'<option '+(r.dataQuality===q?"selected":"")+'>'+q+'</option>').join("")+'</select></label><label>Tags<input id="rtags" '+rd+' value="'+esc(tags(r.classificationTags).join("; "))+'"></label><label>Notes<textarea id="rnotes" '+rd+'>'+esc(r.notes||"")+'</textarea></label>'}
function recordFields(type,r,ro){const rd=ro?"readonly":""; if(type==="Fuel")return '<div class="row"><label>Date<input type="date" id="rdate" '+rd+' value="'+esc(r.date||"")+'"></label><label>Time<input type="time" id="rtime" '+rd+' value="'+esc(r.time||"")+'"></label></div><div class="row"><label>Odometer<input type="number" step="0.01" id="rodo" '+rd+' value="'+esc(r.odometer)+'"></label><label>Miles<input type="number" step="0.01" id="rmiles" '+rd+' value="'+esc(r.miles)+'"></label></div><div class="row"><label>Gallons<input type="number" step="0.001" id="rgal" '+rd+' value="'+esc(r.gallons)+'"></label><label>MPG<input type="number" step="0.01" id="rmpg" '+rd+' value="'+esc(r.mpg)+'"></label></div><label>Station<input id="rstation" '+rd+' value="'+esc(r.station||"")+'"></label>'+commonFields(r,ro); if(type==="Maintenance")return '<label>Drop-Off Date<input type="date" id="rdrop" '+rd+' value="'+esc(r.dropOffDate||"")+'"></label><label>Category<input id="rcat" '+rd+' value="'+esc(r.category||"")+'"></label><label>Cost<input type="number" step="0.01" id="rcost" '+rd+' value="'+esc(r.totalCost)+'"></label>'+commonFields(r,ro); if(type==="Insurance")return '<label>Company<input id="rcompany" '+rd+' value="'+esc(r.company||"")+'"></label><label>Policy Number<input id="rpol" '+rd+' value="'+esc(r.policyNumber||"")+'"></label><label>Effective<input type="date" id="reff" '+rd+' value="'+esc(r.effectiveDate||"")+'"></label><label>Expiration<input type="date" id="rexp" '+rd+' value="'+esc(r.expirationDate||"")+'"></label><label>Premium<input type="number" step="0.01" id="rprem" '+rd+' value="'+esc(r.premium)+'"></label>'+commonFields(r,ro); return commonFields(r,ro)}
function recordView(app,type,id){const r=findRecord(type,id); if(!r)return nav("home"); app.innerHTML=header("View "+type+" Record","home")+'<div class="card">'+recordMeta(r)+recordFields(type,r,true)+'<div class="form-actions"><button onclick="nav(&quot;recordEdit&quot;,{type:&quot;'+type+'&quot;,recordId:&quot;'+id+'&quot;})">Edit</button><button class="danger" onclick="archiveRecord(&quot;'+type+'&quot;,&quot;'+id+'&quot;)">Archive</button></div></div>'+bottomNav()+footer()}
function recordEdit(app,type,id){const r=findRecord(type,id); if(!r)return nav("home"); app.innerHTML=header("Edit "+type+" Record","home")+'<div class="card">'+recordFields(type,r,false)+'<div class="form-actions"><button class="primary" onclick="saveRecordEdit(&quot;'+type+'&quot;,&quot;'+id+'&quot;)">Save Changes</button><button class="danger" onclick="archiveRecord(&quot;'+type+'&quot;,&quot;'+id+'&quot;)">Archive</button></div></div>'+bottomNav()+footer()}
function saveRecordEdit(type,id){const r=findRecord(type,id); if(!r)return; r.dataQuality=$("rq").value; r.classificationTags=$("rtags").value.split(";").map(x=>x.trim()).filter(Boolean); r.notes=$("rnotes").value; r.modifiedAt=nowISO(); if(type==="Fuel"){r.date=$("rdate").value;r.time=$("rtime").value;r.odometer=numVal($("rodo").value);r.miles=numVal($("rmiles").value);r.gallons=numVal($("rgal").value);r.mpg=numVal($("rmpg").value);r.station=$("rstation").value} if(type==="Maintenance"){r.dropOffDate=$("rdrop").value;r.category=$("rcat").value;r.totalCost=numVal($("rcost").value)} if(type==="Insurance"){r.company=$("rcompany").value;r.policyNumber=$("rpol").value;r.effectiveDate=$("reff").value;r.expirationDate=$("rexp").value;r.premium=numVal($("rprem").value)} saveData(); alert("Changes saved."); nav("recordView",{type,recordId:id})}
function archiveRecord(type,id){const r=findRecord(type,id); if(!r)return; if(confirm("Archive this record?")){addTag(r,"Archived"); r.modifiedAt=nowISO(); saveData(); alert("Record archived."); nav("vehicleView",{vehicleId:r.vehicleId})}}

function quickFuel(app,vid){const v=getVehicle(vid), n=new Date(); if(!v)return nav("home"); app.innerHTML=header(vehicleLabel(v)+" - Quick Fuel Entry")+'<div class="card"><div class="row"><label>Date<input type="date" id="fdate" value="'+n.toISOString().slice(0,10)+'"></label><label>Time<input type="time" id="ftime" value="'+n.toTimeString().slice(0,5)+'"></label></div><div class="row"><label>Odometer<input type="number" step="0.01" id="fodo" oninput="calcFuel(&quot;'+vid+'&quot;)"></label><label>Miles<input type="number" step="0.01" id="fmiles" oninput="calcMpg()"></label></div><div class="row"><label>Gallons<input type="number" step="0.001" id="fgal" oninput="calcMpg()"></label><label>MPG<input type="number" step="0.01" id="fmpg" readonly></label></div><div class="row"><label>Fuel Grade<select id="fgrade">'+FUEL_GRADES.map(g=>'<option>'+g+'</option>').join("")+'</select></label><label>Ethanol Free<select id="fef"><option></option><option>Yes</option><option>No</option></select></label></div><label>Station<select id="fstation">'+state.stations.map(s=>'<option>'+esc(s)+'</option>').join("")+'</select></label><div class="row"><label>Price/Gal<input type="number" step="0.01" id="fprice" oninput="calcCost()"></label><label>Total Cost<input type="number" step="0.01" id="fcost"></label></div><label>Notes<textarea id="fnotes"></textarea></label><button class="wide primary" onclick="saveQuickFuel(&quot;'+vid+'&quot;)">Save Entry</button></div>'+previousRecordsHtml("Fuel",vid)+bottomNav()+footer()}
function previousFuelOdo(vid,odo){const rows=records("Fuel",vid,false).filter(r=>r.odometer!==""&&Number(r.odometer)<Number(odo)).sort((a,b)=>Number(b.odometer)-Number(a.odometer)); return rows[0]?.odometer ?? ""}
function calcFuel(vid){const odo=numVal($("fodo").value), prev=previousFuelOdo(vid,odo); if(odo!==""&&prev!=="")$("fmiles").value=(odo-prev).toFixed(2); calcMpg()}
function calcMpg(){const m=numVal($("fmiles").value), g=numVal($("fgal").value); $("fmpg").value=(m!==""&&g>0)?(m/g).toFixed(2):""; calcCost()}
function calcCost(){const g=numVal($("fgal")?.value), p=numVal($("fprice")?.value); if($("fcost")&&g!==""&&p!=="")$("fcost").value=(g*p).toFixed(2)}
function saveQuickFuel(vid){const r=baseRecord("Fuel",vid,"Manual Entry"); Object.assign(r,{date:$("fdate").value,time:$("ftime").value,odometer:numVal($("fodo").value),miles:numVal($("fmiles").value),gallons:numVal($("fgal").value),mpg:numVal($("fmpg").value),fuelGrade:$("fgrade").value,ethanolFree:$("fef").value,station:$("fstation").value,fuelPricePerGallon:numVal($("fprice").value),totalFuelCost:numVal($("fcost").value),fuelCostSource:$("fcost").value?"Calculated":"",notes:$("fnotes").value,attachments:[]}); if(r.odometer!==""&&r.miles==="")addTag(r,"Historical"); state.fuelRecords.push(r); saveData(); alert("Fuel entry saved."); nav("home")}

function quickMaintenance(app,vid){app.innerHTML=header("Quick Maintenance Entry")+'<div class="card"><label>Drop-Off Date<input type="date" id="mdrop"></label><label>Category<input id="mcat"></label><label>Odometer<input type="number" step="0.01" id="modo"></label><label>Cost<input type="number" step="0.01" id="mcost"></label><label>Notes<textarea id="mnotes"></textarea></label><button class="wide primary" onclick="saveQuickMaintenance(&quot;'+vid+'&quot;)">Save Maintenance</button></div>'+previousRecordsHtml("Maintenance",vid)+bottomNav()+footer()}
function saveQuickMaintenance(vid){const r=baseRecord("Maintenance",vid,"Manual Entry"); Object.assign(r,{dropOffDate:$("mdrop").value,category:$("mcat").value||"Maintenance",odometer:numVal($("modo").value),totalCost:numVal($("mcost").value),notes:$("mnotes").value,attachments:[]}); state.maintenanceRecords.push(r); saveData(); alert("Maintenance saved."); nav("vehicleView",{vehicleId:vid})}
function quickInsurance(app,vid){app.innerHTML=header("Quick Insurance Entry")+'<div class="card"><label>Company<input id="icomp"></label><label>Policy Number<input id="ipol"></label><label>Effective Date<input type="date" id="ieff"></label><label>Expiration Date<input type="date" id="iexp"></label><label>Premium<input type="number" step="0.01" id="iprem"></label><label>Notes<textarea id="inotes"></textarea></label><button class="wide primary" onclick="saveQuickInsurance(&quot;'+vid+'&quot;)">Save Policy</button></div>'+previousRecordsHtml("Insurance",vid)+bottomNav()+footer()}
function saveQuickInsurance(vid){const r=baseRecord("Insurance",vid,"Manual Entry"); Object.assign(r,{company:$("icomp").value,policyNumber:$("ipol").value,effectiveDate:$("ieff").value,expirationDate:$("iexp").value,premium:numVal($("iprem").value),notes:$("inotes").value,attachments:[]}); state.insuranceRecords.push(r); saveData(); alert("Insurance policy saved."); nav("vehicleView",{vehicleId:vid})}

function dataScreen(app){app.innerHTML=header("Data Management")+'<div class="card"><h2>Backup & Restore</h2><button class="wide primary" onclick="downloadBackup()">Create JSON Backup</button><label>Restore JSON<input type="file" id="restoreFile" accept=".json"></label><button class="wide" onclick="restoreBackup()">Restore JSON Backup</button><pre id="dataStatus" class="small"></pre></div><div class="card"><h2>CSV Import</h2><p class="muted">CSV import preview. XLSX remains deferred.</p><label>Vehicle<select id="importVehicle">'+state.vehicles.filter(Boolean).map(v=>'<option value="'+v.vehicleId+'">'+esc(vehicleLabel(v))+'</option>').join("")+'</select></label><label>CSV File<input type="file" id="csvFile" accept=".csv"></label><button class="wide" onclick="previewCSV()">Preview Import</button><button class="wide primary" onclick="savePreviewRows()">Save Reviewed Rows</button><pre id="importStatus" class="small"></pre></div>'+bottomNav()+footer()}
function backupPayload(){const p=JSON.parse(JSON.stringify(state)); p.app="RGB Mileage"; p.schemaVersion="2.1.0"; p.exportedAt=nowISO(); p.exportedByVersion=VERSION; p.backupType="Full JSON"; p.metadata={vehicleCount:state.vehicles.filter(Boolean).length,fuelRecordCount:state.fuelRecords.length,maintenanceRecordCount:state.maintenanceRecords.length,insuranceRecordCount:state.insuranceRecords.length,attachmentCount:state.attachments.length}; return p}
function downloadBackup(){const p=backupPayload(), txt=JSON.stringify(p,null,2); if(!confirm("Backup Summary\\nVehicles: "+p.metadata.vehicleCount+"\\nFuel: "+p.metadata.fuelRecordCount+"\\nMaintenance: "+p.metadata.maintenanceRecordCount+"\\nInsurance: "+p.metadata.insuranceRecordCount+"\\nEstimated Size: "+new Blob([txt]).size+" bytes\\n\\nCreate backup?"))return; const a=document.createElement("a"); a.href=URL.createObjectURL(new Blob([txt],{type:"application/json"})); a.download="RGBM_Backup_v"+VERSION+"_"+new Date().toISOString().slice(0,10)+".json"; a.click(); URL.revokeObjectURL(a.href); state.settings.lastBackupDate=nowISO(); saveData()}
function restoreBackup(){const f=$("restoreFile").files[0]; if(!f)return alert("Choose a JSON backup first."); const r=new FileReader(); r.onload=()=>{try{const d=normalizeData(JSON.parse(r.result)); if(confirm("Restore Summary\\nVehicles: "+d.vehicles.filter(Boolean).length+"\\nFuel: "+d.fuelRecords.length+"\\nMaintenance: "+d.maintenanceRecords.length+"\\nInsurance: "+d.insuranceRecords.length+"\\n\\nThis replaces current data.")){saveData(d); alert("Restore complete."); nav("home")}}catch(e){alert("Restore failed: invalid or unsupported JSON.")}}; r.readAsText(f)}
let previewRows=[];
function parseCSV(t){const rows=[]; let row=[], cell="", q=false; for(let i=0;i<t.length;i++){const ch=t[i], nx=t[i+1]; if(ch=='"'&&q&&nx=='"'){cell+='"';i++;continue} if(ch=='"'){q=!q;continue} if(ch==","&&!q){row.push(cell);cell="";continue} if((ch=="\\n"||ch=="\\r")&&!q){if(ch=="\\r"&&nx=="\\n")i++; row.push(cell); if(row.some(x=>x.trim()))rows.push(row); row=[]; cell=""; continue} cell+=ch} row.push(cell); if(row.some(x=>x.trim()))rows.push(row); return rows}
function previewCSV(){const file=$("csvFile").files[0]; if(!file)return alert("Choose a CSV file."); const reader=new FileReader(); reader.onload=()=>{const parsed=parseCSV(reader.result); if(parsed.length<2){$("importStatus").textContent="No records.";return} const headers=parsed[0].map(h=>h.trim()); const idx=n=>headers.findIndex(h=>h.toLowerCase()===n.toLowerCase()); const get=(row,n)=>{const x=idx(n); return x>=0?row[x]:""}; const vid=$("importVehicle").value; previewRows=parsed.slice(1).map(row=>normFuel({recordId:get(row,"recordId")||get(row,"Record ID")||uid("FUELIMP"),entrySequence:Number(get(row,"entrySequence")||get(row,"Entry Sequence"))||seq(),source:get(row,"source")||"CSV Import",classificationTags:(get(row,"classificationTags")||"Imported").split(";").map(x=>x.trim()).filter(Boolean),dataQuality:get(row,"dataQuality")||"Review",date:get(row,"date")||get(row,"Date"),time:get(row,"time")||get(row,"Time"),odometer:get(row,"odometer")||get(row,"Odometer"),miles:get(row,"miles")||get(row,"Total Miles"),gallons:get(row,"gallons")||get(row,"Gallons"),mpg:get(row,"mpg")||get(row,"MPG"),fuelGrade:get(row,"fuelGrade")||get(row,"Fuel Grade"),ethanolFree:get(row,"ethanolFree")||get(row,"Ethanol Free"),station:get(row,"station")||get(row,"Fuel Station"),notes:get(row,"notes")||get(row,"Notes")},vid)); $("importStatus").textContent="Preview complete.\\nRows ready: "+previewRows.length+"\\nDuplicates: "+previewRows.filter(r=>state.fuelRecords.some(e=>e.recordId===r.recordId)).length}; reader.readAsText(file)}
function savePreviewRows(){if(!previewRows.length)return alert("Preview first."); let imported=0, skipped=0; const existing=new Set(state.fuelRecords.map(r=>r.recordId)); previewRows.forEach(r=>{if(existing.has(r.recordId)){skipped++;return} state.fuelRecords.push(r); existing.add(r.recordId); imported++}); saveData(); $("importStatus").textContent="Import Summary\\nImported: "+imported+"\\nSkipped existing: "+skipped; previewRows=[]}
function reports(app){const fuel=state.fuelRecords.filter(r=>!hasTag(r,"Archived")&&!hasTag(r,"Historical")); const miles=fuel.reduce((a,r)=>a+(+r.miles||0),0), gal=fuel.reduce((a,r)=>a+(+r.gallons||0),0); app.innerHTML=header("Reports")+'<div class="grid2"><div class="kpi"><span>Fuel Records</span><b>'+fuel.length+'</b></div><div class="kpi"><span>Average MPG</span><b>'+(gal?(miles/gal).toFixed(2):"")+'</b></div><div class="kpi"><span>Maintenance</span><b>'+state.maintenanceRecords.filter(r=>!hasTag(r,"Archived")).length+'</b></div><div class="kpi"><span>Insurance</span><b>'+state.insuranceRecords.filter(r=>!hasTag(r,"Archived")).length+'</b></div></div><div class="card"><p class="muted">Default reports exclude Historical and Archived records.</p></div>'+bottomNav()+footer()}
function settings(app){app.innerHTML=header("Settings")+'<div class="card"><h2>About</h2><p>RGB Mileage v'+VERSION+'<br>Build Date: '+BUILD_DATE+'<br>Schema: v2.1.0</p><button class="wide danger" onclick="if(confirm(&quot;Clear all local data?&quot;)){localStorage.removeItem(KEY);state=blankData();saveData();nav(&quot;home&quot;)}">Clear Local Data</button></div>'+bottomNav()+footer()}

state=loadData(); render();
if("serviceWorker" in navigator){navigator.serviceWorker.register("sw.js?v=210").catch(()=>{})}
